# ~/.tmux.conf

# Options to make tmux more pleasant
set -g mouse on
set -g default-terminal "tmux-256color"

# Neovim recommendations
set-option -sg escape-time 10
set-option -g focus-events on

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Source TokyoNight theme
source-file ~/.config/tmux/tokyonight_day.tmux

run ~/.config/tmux/plugins/tmux-plugins/tmux-cpu/cpu.tmux