# ~/.tmux.conf

# Options to make tmux more pleasant
set -g mouse on
set -g default-terminal "tmux-256color"

# Source TokyoNight theme
source-file ~/.config/tmux/tokyonight_day.tmux

run ~/.config/tmux/plugins/tmux-plugins/tmux-cpu/cpu.tmux