[tools]
bottom = "latest"
chezmoi = "latest"
eza = "latest"
github-cli = "latest"
lazygit = "latest"
starship = "latest"
usage = "latest"
uv = "latest"
node = "latest"
npm = "latest"
tmux = "latest"
fastfetch = "latest"
neovim = "latest"
tree-sitter = "latest"
ripgrep = "latest"
fzf = "latest"
fd = "latest"
rust = "latest"
opencode = "latest"